// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

/** Extrai o project ref do host Supabase (ex.: https://abc.supabase.co → abc). */
function projectRefFromUrl(url: string): string | null {
  const match = url.match(/https:\/\/([^.]+)\.supabase\.co/i);
  return match?.[1] ?? null;
}

/** Lê o campo `ref` do JWT sem validar assinatura (só para diagnóstico de .env). */
function projectRefFromJwt(token: string): string | null {
  try {
    const payload = token.split(".")[1];
    if (!payload) return null;
    const base64 = payload.replace(/-/g, "+").replace(/_/g, "/");
    const json = JSON.parse(atob(base64));
    return typeof json.ref === "string" ? json.ref : null;
  } catch {
    return null;
  }
}

function assertSupabaseAdminEnvMatch(url: string, serviceRoleKey: string) {
  // Chaves novas do Supabase (sb_secret_*) não são JWT — validação por ref não se aplica
  if (serviceRoleKey.startsWith("sb_secret_") || serviceRoleKey.startsWith("sbp_")) return;

  const urlRef = projectRefFromUrl(url);
  const keyRef = projectRefFromJwt(serviceRoleKey);
  if (!urlRef || !keyRef || urlRef === keyRef) return;

  throw new Error(
    `SUPABASE_URL aponta para o projeto "${urlRef}", mas a service role key é do projeto "${keyRef}". ` +
      `No painel do Supabase, abra o projeto "${urlRef}" → Settings → API e copie a chave "service_role" desse mesmo projeto. ` +
      `Não use prefixo VITE_ nessa chave (ela só roda no servidor).`,
  );
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY =
    process.env.SUPABASE_SERVICE_ROLE_KEY ??
    process.env.SUPABASE_SERVICE_KEY ??
    process.env.SUPABASE_SECRET_KEY;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    throw new Error(
      "Missing Supabase server environment variables. Ensure SUPABASE_URL and one of SUPABASE_SERVICE_ROLE_KEY/SUPABASE_SERVICE_KEY/SUPABASE_SECRET_KEY are set."
    );
  }

  assertSupabaseAdminEnvMatch(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
